// ぽよぽよブラスト V2：ステージ
//
// layout の文字：
//   "." 色のぽよ（ランダム） / " " 盤面の外 / "0"〜"4" 決まった色のぽよ
//   "B" 木箱 / "b" 木箱（2回） / "S" 石 / "L" ふうせん / "G" プレゼント
// colors：使う色の数（0 赤・1 黄・2 青・3 緑・4 紫）
// goals：
//   { type: "color", color, count }               その色のぽよを count 個
//   { type: "box" | "stone" | "balloon" | "gift", count }
//   { type: "combo", min, count }                 min COMBO 以上を count 回
//   { type: "use", booster: "mini" | "rocket" | "bomb" | "disco" | "any", count }  そのブースターを count 回発動
//   { type: "fusion", count }                     ブースターの合体を count 回
// stars：2つ星・3つ星になる点数（1つ星はクリア）。scripts/check-blast.js のボットで決めた目安
// tip：ステージの始めに出す、ひとことの説明 / tutorial：指のお手本（"tap" "drag" "chain"）

const POP_LEVELS = [
  {
    id: 1,
    cols: 7,
    rows: 7,
    colors: 4,
    moves: 14,
    goals: [{ type: "color", color: 0, count: 14 }],
    stars: [11000, 16400],
    tip: "同じ色が2つ以上くっついている所をタップ！",
    tutorial: "tap",
  },
  {
    id: 2,
    cols: 7,
    rows: 8,
    colors: 4,
    moves: 16,
    layout: [
      ".......",
      ".......",
      ".......",
      ".......",
      ".......",
      "1210213",
      "3002031",
      "1313132",
    ],
    goals: [
      { type: "use", booster: "mini", count: 1 },
      { type: "color", color: 2, count: 14 },
    ],
    stars: [14100, 32400],
    tip: "ぽよはドラッグで2マスまで動かせる。4つそろえてタップで「ぷちボム」！",
    tutorial: "drag",
  },
  {
    id: 3,
    cols: 7,
    rows: 8,
    colors: 4,
    moves: 15,
    layout: [
      ".......",
      ".......",
      ".......",
      ".......",
      ".......",
      "...0...",
      "...2...",
      "0002...",
    ],
    goals: [{ type: "combo", min: 2, count: 3 }],
    stars: [13700, 22800],
    tip: "落ちてきたぽよが4つそろうと、自動で消える＝連鎖！",
    tutorial: "chain",
  },
  {
    id: 4,
    cols: 8,
    rows: 8,
    colors: 5,
    moves: 18,
    layout: [
      "........",
      "........",
      "........",
      "BB....BB",
      "BBB..BBB",
      "........",
      "........",
      "........",
    ],
    goals: [
      { type: "box", count: 10 },
      { type: "combo", min: 2, count: 3 },
    ],
    stars: [12100, 23400],
    tip: "5色になった！ 消す前に「どれが落ちてくるか」を見よう。",
  },
  {
    id: 5,
    cols: 8,
    rows: 9,
    colors: 5,
    moves: 20,
    layout: [
      "........",
      "........",
      ".L....L.",
      "........",
      "...LL...",
      "........",
      "L......L",
      "........",
      "..L..L..",
    ],
    goals: [
      { type: "use", booster: "rocket", count: 3 },
      { type: "balloon", count: 8 },
    ],
    stars: [16600, 30400],
    tip: "5つでロケット。連鎖で消えると、少ない数でも強いブースターになる！",
  },
  {
    id: 6,
    cols: 8,
    rows: 9,
    colors: 5,
    moves: 20,
    layout: [
      "  ....  ",
      " ...... ",
      "........",
      "........",
      "........",
      "........",
      "........",
      " ...... ",
      "  ....  ",
    ],
    goals: [
      { type: "combo", min: 3, count: 2 },
      { type: "color", color: 0, count: 25 },
    ],
    stars: [15000, 26000],
    tip: "3 COMBO を2回！ 2段がまえの連鎖を仕込もう。",
  },
  {
    id: 7,
    cols: 8,
    rows: 9,
    colors: 5,
    moves: 22,
    layout: [
      "..G..G..",
      "........",
      "........",
      "...G....",
      "........",
      "........",
      "........",
      "........",
      "........",
    ],
    goals: [
      { type: "gift", count: 3 },
      { type: "combo", min: 3, count: 2 },
    ],
    stars: [19800, 28900],
    tip: "プレゼントは、いちばん下まで落とそう！",
  },
  {
    id: 8,
    cols: 9,
    rows: 9,
    colors: 5,
    moves: 26,
    layout: [
      ".........",
      ".........",
      "..S...S..",
      ".bB...Bb.",
      ".........",
      ".bB...Bb.",
      "..S...S..",
      ".........",
      ".........",
    ],
    goals: [
      { type: "stone", count: 4 },
      { type: "box", count: 8 },
      { type: "use", booster: "bomb", count: 1 },
    ],
    stars: [30100, 37200],
    tip: "石はブースターでしか壊れない！ 6つでボム。",
  },
  {
    id: 9,
    cols: 8,
    rows: 9,
    colors: 5,
    moves: 22,
    layout: [
      "........",
      "........",
      ".R..O...",
      "L......L",
      "........",
      "..L..L..",
      "...M..V.",
      "L.L..L.L",
      "........",
    ],
    goals: [
      { type: "fusion", count: 2 },
      { type: "balloon", count: 8 },
    ],
    stars: [23600, 31200],
    tip: "ブースターもドラッグできる。となりに並べてタップ＝合体！",
  },
  {
    id: 10,
    cols: 9,
    rows: 10,
    colors: 5,
    moves: 24,
    spawnBalloons: 0.05,
    layout: [
      " ....... ",
      ".........",
      "..G...G..",
      ".........",
      ".L.L.L.L.",
      ".........",
      ".........",
      "L.L...L.L",
      ".........",
      " ....... ",
    ],
    goals: [
      { type: "combo", min: 4, count: 1 },
      { type: "balloon", count: 14 },
      { type: "gift", count: 2 },
    ],
    stars: [28900, 37500],
    tip: "4 COMBO に挑戦！ 上からふうせんも降ってくる。",
  },
  {
    id: 11,
    cols: 9,
    rows: 9,
    colors: 5,
    moves: 24,
    goals: [
      { type: "combo", min: 5, count: 1 },
      { type: "color", color: 2, count: 40 },
    ],
    stars: [25800, 37200],
    tip: "5 COMBO を1回！ 下から順に、段を重ねて仕込もう。",
  },
  {
    id: 12,
    cols: 9,
    rows: 10,
    colors: 5,
    moves: 30,
    layout: [
      " ... ... ",
      ".........",
      ".........",
      ".bS...Sb.",
      "..B...B..",
      ".........",
      " ....... ",
      "  BbSbB  ",
      "   ...   ",
      "    .    ",
    ],
    goals: [
      { type: "box", count: 8 },
      { type: "stone", count: 3 },
      { type: "combo", min: 4, count: 2 },
    ],
    stars: [30300, 37000],
    tip: "最後のステージ！ 4 COMBO を2回決めよう。",
  },
];

if (typeof module !== "undefined") module.exports = POP_LEVELS;
