// ぽよぽよブラスト：ステージ
//
// layout の文字：
//   "." 色のぽよ（ランダム） / " " 盤面の外 / "0"〜"4" 決まった色のぽよ
//   "B" 木箱 / "b" 木箱（2回） / "S" 石 / "L" ふうせん / "G" プレゼント
// colors：使う色の数（0 赤・1 黄・2 青・3 緑・4 紫）
// goals：{ type: "color", color, count } / { type: "box" | "stone" | "balloon" | "gift", count }
// stars：2つ星・3つ星になる点数（1つ星はクリア）。scripts/check-blast.js のボットで決めた目安
// tip：ステージの始めに出す、ひとことの説明

const POP_LEVELS = [
  {
    id: 1,
    cols: 7,
    rows: 7,
    colors: 3,
    moves: 18,
    goals: [{ type: "color", color: 0, count: 15 }],
    stars: [8000, 8900],
    tip: "同じ色が2つ以上くっついている所をタップ！",
    tutorial: true,
  },
  {
    id: 2,
    cols: 7,
    rows: 8,
    colors: 4,
    moves: 20,
    goals: [
      { type: "color", color: 2, count: 18 },
      { type: "color", color: 3, count: 18 },
    ],
    stars: [7300, 9000],
    tip: "5個以上まとめて消すと「ロケット」ができる！",
  },
  {
    id: 3,
    cols: 8,
    rows: 8,
    colors: 4,
    moves: 22,
    layout: [
      "........",
      "........",
      "........",
      "BB....BB",
      "BBB..BBB",
      "........",
      "........",
      "........",
    ],
    goals: [{ type: "box", count: 10 }],
    stars: [8800, 10100],
    tip: "木箱は、となりで消すと壊れるよ。",
  },
  {
    id: 4,
    cols: 8,
    rows: 9,
    colors: 4,
    moves: 23,
    layout: [
      "........",
      "........",
      ".L....L.",
      "........",
      "...LL...",
      "........",
      "L......L",
      "........",
      "..L..L..",
    ],
    goals: [
      { type: "balloon", count: 8 },
      { type: "color", color: 1, count: 25 },
    ],
    stars: [9600, 11500],
    tip: "7個以上で「ボム」！ ふうせんは、となりで消すと割れる。",
  },
  {
    id: 5,
    cols: 8,
    rows: 9,
    colors: 4,
    moves: 24,
    layout: [
      "  ....  ",
      " ...... ",
      "........",
      "........",
      "........",
      "........",
      "........",
      " ...... ",
      "  ....  ",
    ],
    goals: [
      { type: "color", color: 0, count: 30 },
      { type: "color", color: 2, count: 30 },
    ],
    stars: [8400, 10600],
    tip: "9個以上で「レインボー」！ その色をぜんぶ消す。",
  },
  {
    id: 6,
    cols: 8,
    rows: 9,
    colors: 4,
    moves: 25,
    layout: [
      "........",
      "........",
      "........",
      "B.bBBb.B",
      "........",
      "........",
      "BbB..BbB",
      "........",
      "........",
    ],
    goals: [{ type: "box", count: 12 }],
    stars: [9400, 11200],
    tip: "ブースター同士がとなりなら、タップで合体して超強力に！",
  },
  {
    id: 7,
    cols: 8,
    rows: 9,
    colors: 4,
    moves: 24,
    layout: [
      "..G..G..",
      "........",
      "........",
      "...G....",
      "........",
      "........",
      "........",
      "........",
      "........",
    ],
    goals: [
      { type: "gift", count: 3 },
      { type: "color", color: 3, count: 30 },
    ],
    stars: [9800, 12700],
    tip: "プレゼントを、いちばん下まで落とそう！",
  },
  {
    id: 8,
    cols: 9,
    rows: 9,
    colors: 4,
    moves: 33,
    layout: [
      ".........",
      ".........",
      "..S...S..",
      ".bB...Bb.",
      ".........",
      ".bB...Bb.",
      "..S...S..",
      ".........",
      ".........",
    ],
    goals: [
      { type: "stone", count: 4 },
      { type: "box", count: 8 },
    ],
    stars: [11800, 14700],
    tip: "石は、ブースターでしか壊れない！",
  },
  {
    id: 9,
    cols: 9,
    rows: 10,
    colors: 4,
    moves: 28,
    spawnBalloons: 0.05,
    layout: [
      " ....... ",
      ".........",
      "..G...G..",
      ".........",
      ".L.L.L.L.",
      ".........",
      ".........",
      "L.L...L.L",
      ".........",
      " ....... ",
    ],
    goals: [
      { type: "balloon", count: 14 },
      { type: "gift", count: 2 },
    ],
    stars: [13400, 16200],
    tip: "上からも、ふうせんが降ってくる！",
  },
  {
    id: 10,
    cols: 9,
    rows: 10,
    colors: 4,
    moves: 32,
    layout: [
      " ... ... ",
      ".........",
      ".........",
      ".bS...Sb.",
      "..B...B..",
      ".........",
      " ....... ",
      "  BbSbB  ",
      "   ...   ",
      "    .    ",
    ],
    goals: [
      { type: "box", count: 8 },
      { type: "stone", count: 3 },
      { type: "color", color: 3, count: 35 },
    ],
    stars: [10400, 13100],
    tip: "最後のステージ！ ハートの形をクリアしよう。",
  },
];

if (typeof module !== "undefined") module.exports = POP_LEVELS;
